---
title: "物料的新增测试"
author: "胡立磊"
date: "2021/5/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
  #设置全局变量
   conn = vmrdspkg::conn_vm_erp_test()
   param_fnumber = 'RDS.01.000001'
```

## 1、物料创建前检查
### 1.1、 查年上级物相关信息t_Item
```{sql connection=conn}
Select * From (Select t1.* From t_Item t1  WHERE t1.FDeleteD=0  And t1.FItemClassID = 4 And t1.FItemClassID = 4) i  Where 1=1  And (FNumber = 'RDS')


```

详细信息如下：
```{sql connection=conn}
 select i.* from t_Item i where i.FItemID = 21118

```

### 1.2、 查看物料表`r letters[20]`_icitem
    查看表的内容，本质是一个视图
```{sql connection=conn}
   select FSQLTableName, FVersion from t_ItemClass where FItemClassID = 4
```


### 1.3查看上级组物料的内容
```{sql connection= conn}
select * from t_ICItem where FItemID = 21118

```
   我们通过对比1.1与1.3可以看到，上级组的物料只存在于t_item表而不在t_icitem表中

### 1.4、再次确认表名
```{sql connection= conn}
 select FSQLTableName, FVersion,FImport,FGRType from t_ItemClass where FItemClassID = 4

```

### 1.5、查看成本对象的表结构
```{sql connection= conn}
   select FItemClassID,FNumber,FName    from t_itemclass where fitemclassid =2001
```


### 1.6获取所有成本对象的代码
```{sql connection=conn}
Select FNumber from t_item where FItemClassID = 2001

```
   真实情况有(4655 rows affected) 个，在此仅仅显示前10个


## 2、相关基础信息

### 2.1、数据类型信息表
```{sql connection= conn}
   select * from t_DataTypeInfo
```

### 2.2、uuid生成器
```{sql connection=conn}
    Select newid() as UUID
```



## 3. 物料相关信息
### 3.1.物料表的数据字段
```{sql connection=conn}
select FSQLColumnName, FActualType, FActualSize, FDefaultValue, FViewMask, FName from t_ItemPropDesc where FItemClassID = 4
```

### 3.2.相关的字段名如下：
```{sql connection=conn}
  SELECT t1.name,t2.name  FROM SYSOBJECTS t1 ,SYSCOLUMNS t2 WHERE t1.id=t2.id AND t1.Name = 't_ICItem'
```

其中规格型号的字段内容如下
```{sql connection=conn}
select FSQLColumnName, FActualType, FActualSize, FDefaultValue, FViewMask, FName from t_ItemPropDesc where FItemClassID = 4
and FSQLColumnName ='FModel'
```
针对规格型号设置值为空`Update t_ICItem Set FModel='' Where FItemID=21121`


### 3.2A所有物料的字段如下如下
```{sql connection= conn}

  SELECT t2.name as FFieldName,t1.name as FTableName
  FROM SYSOBJECTS t1 ,SYSCOLUMNS t2 WHERE t1.id=t2.id AND 
  t1.Name in
  (
  't_Item',
't_ICItemBase',
't_ICItemCore',
't_ICItemMaterial',
't_ICItemPlan',
't_ICItemDesign',
't_ICItemStandard',
't_ICItemQuality',
'T_BASE_ICItemEntrance',
't_ICItemCustom',
't_BaseProperty'

  )

```




### 3.3 物料权限表t_ItemRight-实际没有使用
```{sql connection=conn}
   select * from t_ItemRight
```

  实际情况没有使用
   Insert Into t_ItemRight (FTypeID,FUserID,FItemID) 
 select fitemclassid,fuserid,21121 from t_useritemclassright 
 where (( FUserItemClassRight &  8)=8) and fitemclassid=4 and fuserid<>16394

 相关的物料的查询信息
```{sql connection=conn}
   Select FName,FName_CHT,FName_EN From t_ItemClass Where FItemClassID = 4
```
 
### 3.4 写入日志t_Log
   写入日志等内容

`INSERT INTO t_Log (FDate,FUserID,FFunctionID,FStatement,FDescription,FMachineName,FIPAddress) 
VALUES (getdate(),16394,'A00701',5,'新建核算项目:RDS.0002 核算项目类别:物料','RDSTSM','10.105.31.24')
select 'ok' as result`
 

### 3.5 写入基础资料属性表t_BaseProperty
```{sql connection=conn}
   Select * from t_BaseProperty Where  FItemID = 21121
```
   用于在物料基础资料中，找到相应的物料，右键，点相关属性。
   写入基础资料属性表的相关内容
   Insert Into t_BaseProperty(FTypeID, FItemID, FCreateDate, FCreateUser, FLastModDate, FLastModUser, FDeleteDate, FDeleteUser)Values(3, 21121, '2021-01-04 12:48:54', 'administrator', Null, Null, Null, Null)
go


### 3.6 数据行权限控制t_AccessRowData
```{sql connection=conn}
Select FAccessType,FAccessColName,FAccessTable,FUsed  from t_AccessRowData where FType=1 and FClassID=4
```
相关的全部的字段内容如下
```{sql connection=conn}
Select  *  from t_AccessRowData where FType=1 and FClassID=4

```




### 3.7 写入物料控制表Access_t_ICItem
 先删除相关的字段
Delete from Access_t_ICItem where FItemID=21121
然后再写入

Insert into Access_t_ICItem(FItemID,FParentIDX,FDataAccessView,FDataAccessEdit,FDataAccessDelete)
 Values(21121,21118,convert(varbinary(7200),REPLICATE(char(255),100)),convert(varbinary(7200),REPLICATE(char(255),100)),convert(varbinary(7200),REPLICATE(char(255),100)))
 
 
### 3.8写入物料权限控制t_gr_itemcontrol
 delete from  t_gr_itemcontrol where FItemID=21121 and FItemClassID=4
 将上级物料的相关属性进行写入
insert into t_gr_itemcontrol(FFrameWorkID,FItemClassID,FItemID,FCanUse,FCanAdd,FCanModi,FCanDel)
select FFrameWorkID,FItemClassID,21121,FCanUse,FCanAdd,FCanModi,FCanDel
from t_gr_itemcontrol where FItemID=21118 and FItemClassID=4


### 3.9更新物料主数据的时间戳
    update t_Item set FName=FName where FItemID=21121 and FItemClassID=4
    
### 3.10 更新全称为一致的全称

   UPDATE t1  SET t1.FFullName = t2.FFullName FROM t_ICItemBase t1 
   
   INNER JOIN t_Item t2 ON t1.FItemID = t2.FItemID AND t2.FItemID =21121
   
   
## 4.物料的详细表结构分析
###  4.1主表
#### 外购物料

```{sql connection=conn}
   select  *    from  t_Item  where FNumber = 'RDS.01.000001'
   
```

```{sql connection=conn}
 select  *    from  t_Item  where fitemid = 21129
```

#### 自制物料
```{sql connection=conn}
   select  *    from  t_Item  where FNumber = 'RDS.02.000001'
   
```
   查询到2条记录，其中一条为物料，另外一条为成本对象
   如果仅仅看到物料
```{sql connection=conn}
   select  *    from  t_Item  where FNumber = 'RDS.02.000001'
   and fitemclassid =4
   
```   
   注意物料与成本对象使用不同的内码
```{sql connection=conn}
 select  *    from  t_Item  where fitemid = 21130
```   
   
#### 委外物料

```{sql connection=conn}
   select  *    from  t_Item  where FNumber = 'RDS.03.000001'
   
```

   注：委外的物料***没有成本对象*** 有点意外了
   
```{sql connection=conn}
 select  *    from  t_Item  where fitemid = 21132
```   
      
   
   
   
### 4.2 物料视图

#### 外购物料
```{sql connection=conn}
select  *  from t_ICItem where FNumber ='RDS.01.000001'
```

```{sql connection=conn}
select  *  from t_ICItem  where fitemid = 21129
```

#### 自制物料

```{sql connection=conn}
select  *  from t_ICItem where FNumber ='RDS.02.000001'
```


```{sql connection=conn}
select  *  from t_ICItem  where fitemid = 21130
```


#### 委外物料

```{sql connection=conn}
select  *  from t_ICItem where FNumber ='RDS.03.000001'
```


```{sql connection=conn}
select  *  from t_ICItem  where fitemid = 21132
```


### 4.2.1A 物料基本信息表

#### 外购物料
```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```

```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID = 21129

```
#### 自制物料

```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID = 21130

```

#### 委外物料

```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')
```


```{sql connection=conn}
select *  from t_ICItemBase  where  FItemID = 21132

```


### 4.2.1.B 物料核心表

#### 外购物料

```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```

```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID = 21129
```

#### 自制物料

```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```

```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID = 21130
```


#### 委外物料


```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')
```

```{sql connection=conn}
select  *  from t_ICItemCore  where  FItemID = 21132
```




### 4.2.2 物料物流资料页签

#### 外购物料

```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```


```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID = 21129
```


#### 自制物料
```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID = 21130
```


#### 委外物料

```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')
```


```{sql connection=conn}
select   *     from t_ICItemMaterial  where  FItemID = 21132
```


### 4.2.3 物料计划资料页签

#### 外购物料
```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')

```


```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID = 21129

```

#### 自制物料

```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')

```


```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID = 21130

```


#### 委外物料

```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')

```


```{sql connection=conn}
select   *     from t_ICItemPlan  where  FItemID = 21132

```




### 4.2.4 物料设计资料页签

#### 外购物料

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')

```

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID = 21129

```

#### 自制物料

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')

```

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID = 21130

```

#### 委外物料

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')

```

```{sql connection=conn}
select    *      from t_ICItemDesign  where  FItemID = 21132

```





### 4.2.5 物料标准数据页签

#### 外购物料


```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```


```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID = 21129
```

#### 自制物料


```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID = 21130
```


#### 委外物料

```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')
```


```{sql connection=conn}
select   *       from t_ICItemStandard  where  FItemID = 21132
```



### 4.2.6 物料质量资料页签

#### 外购物料
```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```


```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID = 21129
```

#### 自制物料

```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID = 21130
```
#### 委外物料
```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')
```


```{sql connection=conn}
select   *       from t_ICItemQuality  where  FItemID = 21132
```




### 4.2.7 物料进出口资料页签

#### 外购物料
```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')
```


```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID = 21129
```

#### 自制物料

```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID = 21130
```

#### 委外物料
```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')
```


```{sql connection=conn}
select * from T_BASE_ICItemEntrance
where  FItemID = 21130
```




### 4.2.8 物料自定义页签信息表

#### 外购物料 
```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.01.000001')

```

```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID = 21129

```

#### 自制物料
```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.02.000001')

```

```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID = 21130

```

#### 委外物料
```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID
in
(select  FItemID  from  t_Item  where FNumber ='RDS.03.000001')

```

```{sql connection=conn}
select  *   from t_ICItemCustom  where  FItemID = 21132

```





   F113   旧编码
   F114   旧名称
   F_122  层级
   F_124  是否配件
   F_125  9


###  4.2.9 物料相关属性

#### 外购物料

```{sql connection=conn}

Select * from t_BaseProperty Where  FItemID = 21129
```

#### 自制物料

```{sql connection=conn}

Select * from t_BaseProperty Where  FItemID = 21130
```

### 委外物料
```{sql connection=conn}

Select * from t_BaseProperty Where  FItemID = 21132
```



## 4.3物料权限控表

### 外购物料
```{sql connection=conn}
   select * from  Access_t_ICItem where FItemID=21129
```

### 自制物料

```{sql connection=conn}
   select * from  Access_t_ICItem where FItemID=21130
```

### 委外物料

```{sql connection=conn}
   select * from  Access_t_ICItem where FItemID=21132
```



## 4.4物料写入日志
```{sql connection=conn}
select * from t_log where FDescription like '新建核算项目:%核算项目类别:物料'
```


## 4.5 成本对象
### 外购物料
```{sql connection=conn}
    select * from cbCostObj where  FNumber ='RDS.01.000001'

```

### 自制物料
```{sql connection=conn}
    select * from cbCostObj where  FNumber ='RDS.02.000001'

```

### 委外物料

```{sql connection=conn}
    select * from cbCostObj where  FNumber ='RDS.03.000001'

```



